# ~/.config/alacritty/alacritty.toml
[general]
import = ["~/.config/alacritty/current_theme.toml"]

[font]
size = 13.5

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"


[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[keyboard]
bindings = [
  # Ctrl+Tab → send custom escape sequence to tmux
  { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
  # Ctrl+Shift+Tab → send custom escape sequence to tmux
  { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]

[window]
dimensions = { columns = 100, lines = 32 }

opacity = 1.0
dynamic_title = true

[window.padding]
x = 5
y = 2

[cursor]
style = "Block"
unfocused_hollow = true
