require("plugin_options.lsp")
require("plugin_options.comment-nvim")
require("plugin_options.nvim-cmp")
require("plugin_options.nvim-lint")
require("plugin_options.nvim-tree")
require("plugin_options.telescope")
require("plugin_options.todo-comments")
require("plugin_options.treesitter")
